/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    BaseDatePicker: (typeof import("./src/components/UI/BaseDatePicker.vue"))["default"];
    BaseDialog: (typeof import("./src/components/UI/BaseDialog.vue"))["default"];
    TableView: (typeof import("./src/components/TableView.vue"))["default"];
    TheAppBar: (typeof import("./src/components/TheAppBar.vue"))["default"];
    TheDialog: (typeof import("./src/components/TheDialog.vue"))["default"];
    TheExpensesDialog: (typeof import("./src/components/expenses/TheExpensesDialog.vue"))["default"];
    TheMonthSelector: (typeof import("./src/components/TheMonthSelector.vue"))["default"];
  }
}
