/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDatePicker: typeof import('./src/components/UI/BaseDatePicker.vue')['default']
    BaseDialog: typeof import('./src/components/UI/BaseDialog.vue')['default']
    BaseReportPage: typeof import('./src/components/UI/BaseReportPage.vue')['default']
    ChartTypeButtons: typeof import('./src/components/charts/ChartTypeButtons.vue')['default']
    copy: (typeof import("./src/components/charts/ExpensesBarChart copy.vue"))["default"]
    ExpensesBarChart: typeof import('./src/components/charts/ExpensesBarChart.vue')['default']
    ExpensesPieChart: typeof import('./src/components/charts/ExpensesPieChart.vue')['default']
    IncomeBarChart: typeof import('./src/components/charts/IncomeBarChart.vue')['default']
    IncomePieChart: typeof import('./src/components/charts/IncomePieChart.vue')['default']
    MonthSelector: typeof import('./src/components/MonthSelector.vue')['default']
    NewRecordTemplate: typeof import('./src/components/records/NewRecordTemplate.vue')['default']
    NoDataDiv: typeof import('./src/components/UI/NoDataDiv.vue')['default']
    RecordsExpansionPanels: typeof import('./src/components/records/RecordsExpansionPanels.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableView: (typeof import("./src/components/TableView.vue"))["default"]
    TheAppBar: (typeof import("./src/components/TheAppBar.vue"))["default"]
    TheDialog: (typeof import("./src/components/TheDialog.vue"))["default"]
    TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
    TheIncomeDialog: (typeof import("./src/components/income/TheIncomeDialog.vue"))["default"]
    TheRecordsDialog: (typeof import("./src/components/TheRecordsDialog.vue"))["default"]
    TotalAmountAlert: typeof import('./src/components/records/TotalAmountAlert.vue')['default']
  }
}
